Run go build

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -16,91 +16,130 @@ jobs:
     name: Validate commit
     runs-on: ubuntu-latest
     # Temporarily disable commit validation
-    if: ${{ false && github.ref != 'refs/heads/main' }}
+    if: ${{ github.ref != 'refs/heads/main' }}
     steps:
       - uses: actions/checkout@v4
 
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v4.0.0
+      - name: Setup Go
+        uses: actions/setup-go@v6.1.0
         with:
-          dotnet-version: 8.0.x
+          go-version: '1.24.*'
 
-      - name: Restore dependencies
-        run: dotnet clean && dotnet nuget locals all --clear && dotnet restore
+      - uses: extractions/setup-just@v3
 
-      - name: Test
-        working-directory: ./test
-        run: |
-          dotnet add package coverlet.msbuild
-          dotnet test ${PROJECT_NAME}.Tests.csproj --configuration Debug --runtime linux-x64 /p:CollectCoverage=true /p:CoverletOutput=Coverage/ /p:CoverletOutputFormat=lcov --logger GitHubActions
+      - name: Setup integration tests
+        run: just up
 
-      - name: Publish Code Coverage
-        if: ${{ github.event_name == 'pull_request' && always() }}
-        uses: romeovs/lcov-reporter-action@v0.3.1
+      - name: Check Format
+        run: gofmt -d ./
+
+      - name: Verify dependencies
+        run: go mod verify
+
+      - name: Install dependencies
+        run: go mod vendor
+
+      - name: Run go vet
+        run: go vet ./...
+
+      - name: Build
+        run: go build -v ./...
+
+      - name: Lint
+        uses: golangci/golangci-lint-action@v9
+        with:
+          version: v2.1.0
+
+      - name: Run integration tests
+        run: go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
+
+      - name: Check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2.18.0
+        continue-on-error: true # Should fail after coverage comment is posted
+        with:
+          config: .testcoverage.yaml
+
+      - name: Post coverage report
+        uses: thollander/actions-comment-pull-request@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
-          lcov-file: ./test/Coverage/coverage.info
-              
-      - name: Check style
-        run: dotnet format --verify-no-changes
-          
-  build_image:
-    name: Build Docker Image and Helm Charts
-    runs-on: ubuntu-latest
-    needs: [ validate_commit ]
-    # Temporarily disable image building
-    if: ${{ false && always() && (needs.validate_commit.result == 'success' || needs.validate_commit.result == 'skipped') }}
-    permissions:
-      contents: read
-      packages: write
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with: 
-          fetch-depth: 0
-      
-      - name: Log in to the Container registry
-        uses: docker/login-action@v3.3.0
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          message: |
+            go-test-coverage report:
+            ```${{ fromJSON(steps.coverage.outputs.report) }}```
 
-      - name: Get project version
-        uses: SneaksAndData/github-actions/generate_version@v0.1.6
-        id: version
+      - name: Finally check coverage
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-          tags: |
-            type=semver,pattern={{version}},value=${{steps.version.outputs.version}}
-          flavor:
-            latest=false
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3.3.0
-        with:
-          use: true
-          platforms: linux/arm64,linux/amd64
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5.3.0
-        with:
-          context: .
-          file: .container/Dockerfile
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          platforms: linux/arm64,linux/amd64
-
-      - name: Build and Push Chart
-        uses: SneaksAndData/github-actions/build_helm_chart@v0.1.8
-        with:
-          application: arcane-operator
-          app_version: ${{ steps.meta.outputs.version }}
-          container_registry_user: ${{ github.actor }}
-          container_registry_token: ${{ secrets.GITHUB_TOKEN }}
-          container_registry_address: ghcr.io/sneaksanddata/
+      - name: Get logs from application pods
+        if: always()
+        run: |
+          kubectl describe pods --namespace default || true
+          echo "============================= Logs from boxer-issuer =================================================="
+          kubectl logs -l app.kubernetes.io/name=boxer-issuer || true
+          echo "============================= Logs from boxer-validator-nginx =-======================================="
+          kubectl logs -l app.kubernetes.io/name=boxer-validator-nginx || true
+#
+#  build_image:
+#    name: Build Docker Image and Helm Charts
+#    runs-on: ubuntu-latest
+#    needs: [ validate_commit ]
+#    # Temporarily disable image building
+#    if: ${{ false && always() && (needs.validate_commit.result == 'success' || needs.validate_commit.result == 'skipped') }}
+#    permissions:
+#      contents: read
+#      packages: write
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Log in to the Container registry
+#        uses: docker/login-action@v3.3.0
+#        with:
+#          registry: ${{ env.REGISTRY }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Get project version
+#        uses: SneaksAndData/github-actions/generate_version@v0.1.6
+#        id: version
+#
+#      - name: Extract metadata (tags, labels) for Docker
+#        id: meta
+#        uses: docker/metadata-action@v5
+#        with:
+#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+#          tags: |
+#            type=semver,pattern={{version}},value=${{steps.version.outputs.version}}
+#          flavor:
+#            latest=false
+#
+#      - name: Set up Docker Buildx
+#        uses: docker/setup-buildx-action@v3.3.0
+#        with:
+#          use: true
+#          platforms: linux/arm64,linux/amd64
+#
+#      - name: Build and push Docker image
+#        uses: docker/build-push-action@v5.3.0
+#        with:
+#          context: .
+#          file: .container/Dockerfile
+#          push: true
+#          tags: ${{ steps.meta.outputs.tags }}
+#          labels: ${{ steps.meta.outputs.labels }}
+#          platforms: linux/arm64,linux/amd64
+#
+#      - name: Build and Push Chart
+#        uses: SneaksAndData/github-actions/build_helm_chart@v0.1.8
+#        with:
+#          application: arcane-operator
+#          app_version: ${{ steps.meta.outputs.version }}
+#          container_registry_user: ${{ github.actor }}
+#          container_registry_token: ${{ secrets.GITHUB_TOKEN }}
+#          container_registry_address: ghcr.io/sneaksanddata/
